name: Build and Deploy Docker Image with Nginx and SSL
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build, Push, and Deploy with Nginx and SSL
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Install dependencies and build the Vite app
      - name: Install Dependencies and Build
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install --legacy-peer-deps
          npm install ajv --save
          npm run build

      # Login to Docker Hub
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build Docker Image with only the build folder and Nginx
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/webportfolio:latest .

      # Push Docker Image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/webportfolio:latest

      # Set up SSH Key
      - name: Set up SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Deploy to Server
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull the latest Docker image
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/webportfolio:latest

            # Stop and remove any existing container
            sudo docker stop webportfolio || true
            sudo docker rm webportfolio || true

            # Run the new container with SSL environment variables
            sudo docker run -d -p 80:80 -p 443:443 \
              -e VITE_SSL_CERT_CHAIN="${{ secrets.SSL_CERT_CHAIN }}" \
              -e VITE_SSL_PRIVATE_KEY="${{ secrets.SSL_PRIVATE_KEY }}" \
              --name webportfolio \
              ${{ secrets.DOCKER_USERNAME }}/webportfolio:latest

            # Clean up unused resources without affecting running containers
            sudo docker image prune -af
